services:
  - type: web
    name: stickynotes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 notes:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromDatabase: your_database_name
      - key: DATABASE_URL
        fromDatabase: your_database_name
      - key: UPLOAD_FOLDER
        value: uploads
